name: Publish Testarchiver to Pypi

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
    branches:
      - master
      - develop
jobs:
    build-and-publish:
      name:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@master
        - name: Set up Python 3.8
          uses: actions/setup-python@v1
          with:
            python-version: 3.8
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install setuptools wheel twine
            if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

        - name: Set build number for development builds
          if: ${{ !startsWith(github.ref, 'refs/tags') }}
          run: |
            echo "BUILD_NUMBER_FOR_DEV_PACKAGE_VERSION=$GITHUB_RUN_ID" >> $GITHUB_ENV
        - name: Build a binary wheel and a source tarball
          run: |
            python setup.py sdist bdist_wheel
        - name: Publish to Test PyPI
          uses: pypa/gh-action-pypi-publish@master
          with:
            password: ${{ secrets.test_pypi_api_token }}
            repository_url: https://test.pypi.org/legacy/
        - name: Publish distribution to PyPI
          uses: pypa/gh-action-pypi-publish@master
          with:
            password: ${{ secrets.pypi_api_token }}
